# Generated by Django 4.2.4 on 2023-08-02 08:31

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('current_mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('price_per_day', models.IntegerField()),
                ('price_per_hour', models.IntegerField()),
                ('num_of_passenger', models.IntegerField()),
                ('piece_of_bag', models.IntegerField()),
                ('limit_mileage', models.IntegerField()),
                ('num_of_door', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=10)),
                ('car', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type_and_rate', chained_model_field='type_and_rate', on_delete=django.db.models.deletion.CASCADE, to='rent_car.car')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to='rent_car.officelocation')),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_location', to='rent_car.officelocation')),
                ('type_and_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_car.typerate')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='rent_car.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='rent_car.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='office_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_car.officelocation'),
        ),
        migrations.AddField(
            model_name='car',
            name='type_and_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_rate', to='rent_car.typerate'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_car.car')),
                ('type_and_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_car.typerate')),
            ],
        ),
    ]
