# Generated by Django 4.2.4 on 2023-08-02 10:02

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0002_alter_reservation_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_and_rate',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car', chained_model_field='car', on_delete=django.db.models.deletion.CASCADE, to='rent_car.typerate'),
        ),
    ]
