# Generated by Django 4.2.4 on 2023-08-02 10:16

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0004_alter_reservation_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='car',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type_and_rate', chained_model_field='type_and_rate', on_delete=django.db.models.deletion.CASCADE, to='rent_car.car'),
        ),
    ]
