# Generated by Django 4.2.4 on 2023-08-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0005_alter_availability_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='pickup_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
