# Generated by Django 4.2.4 on 2023-08-02 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0007_alter_availability_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='pickup_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
