# Generated by Django 4.2.4 on 2023-08-08 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0009_alter_availability_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
