# Generated by Django 4.2.4 on 2023-08-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0011_alter_reservation_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_and_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_car.typerate'),
        ),
    ]
