# Generated by Django 4.2.4 on 2023-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0012_alter_reservation_type_and_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=10, null=True),
        ),
    ]
