# Generated by Django 4.2.4 on 2023-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0015_alter_reservation_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='reservation',
        ),
        migrations.AddField(
            model_name='extra',
            name='price_type',
            field=models.CharField(choices=[('Per reservation', 'Per reservation'), ('Per day', 'Per day')], max_length=250, null=True),
        ),
    ]
